### ISSUE TITLE
example file

### ISSUE THREAD

**Issue by yupinglin0301** [TesiNicco/pathway-PRS#1]
Sorry, do you have the example file to run the code? Thanks

**Comment by TesiNicco** [comment]
Hi, thanks for reaching. Apologies, example files were not there.

I just added a better description of the codes and the necessary example files.

Briefly, if you want to replicate the variant-pathway annotation, now it is possible. Please follow the script at **variant_pathway_annotation/VPA_pipeline.sh**. The required files are placed at **example_files_variant_pathway_annotation**

If you want to run the pathway-prs calculation, then follow the steps at **calculate_pathwayPRS**. The required input files are placed at **example_files_pathwayPRS**.

In the REAME.md there are additional information on how to run/replicate.

Let me know how it goes, and if I can help you in any way :)

Best,
Nicco

**Comment by yupinglin0301** [comment]
Hi, Thanks for the detailed explanation.
I will let you know if I need any further help.

Best,
Yu-Ping

**Comment by TesiNicco** [comment]
No worries. I will close the issue for now. 

Best,
Nicco
